# This workflow will do: 
# 1. a clean install of node dependencies, 
# 2. cache/restore them, 
# 3. build the source code and 
# 4. run tests across different versions of node

# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# trigger workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # platform to run this job
    runs-on: ubuntu-latest

    # run test on multiple versions of node
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}
      # sets up nodejs environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # clean install dependecies
    - run: npm ci
      # run test command from package.json in testing environment
    - run: npm test
